# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.


report: "report/workflow.rst"


# Allow users to fix the underlying OS via singularity.
container: "docker://continuumio/miniconda3"


##### check snakemake min version #####

from snakemake.utils import min_version

min_version("7.15.2")


include: "rules/common.smk"
include: "rules/sequence_selection_common.smk"
include: "rules/sequence_selection.smk"
include: "rules/training.smk"
include: "rules/predict.smk"


rule all:
    input:
        # The first rule should define the default target files
        # Subsequent target rules can be specified below. They should start with all_*.
        expand(
            "results/sequence_selection/regions.annotated_bidirectional.{dataset}.bed.gz",
            dataset=["test", "training", "validation"],
        ),
        "results/training/model.json",
        expand(
            "results/predictions/{test_name}.tsv.gz",
            test_name=list(tests.index),
        )
